Data:
  data_dir: "Data"
  backgrounds: "backgrounds"
  positives: "positives"
  negatives: "negatives"
  nn: "NeuralNet"

Seed: 600031800

NeuralNet:
  sample_rate: 16000
  epochs: 100
  batch_size: 32
  eval_batch_size: 32
  lr: 0.0001
  model_name: "wwmodel"
  save_checkpoint_path: "wwmodel"
  train_data_csv: "files/train.csv"
  test_data_csv: "files/test.csv"
  no_cuda: False
  num_workers: 1
  hidden_size: 128